### ISSUE TITLE
Assessment job not started due to error: Microsoft Graph service exception

### ISSUE THREAD

**Issue by zcholla** [pnp/pnpassessment#29]
I am getting the same message each time I attempt to run the assessment tool for the Azure ACS addin. I do not know ow to solve the problem. 

`start --mode AddInsACS --tenant mycompany.sharepoint.com --applicationid abcdef-1234-5678-91ef-abcdefhigf8634`

Assessment job not started due to error: Microsoft Graph service exception

![image](https://github.com/pnp/pnpassessment/assets/20195129/322b125c-ac89-42a0-be6a-a404853b9070)

**Comment by zcholla** [comment]
Problem Solved. I did not have the cert properly installed to the application.

**Comment by zcholla** [comment]
Problem Solved. I did not have the cert properly installed to the application.

**Comment by femilovechild** [comment]
Still having this issue here. Certificate is installed on my local machine, azure app has the certificate listed. Still getting 

Assessment job not started due to error: Microsoft Graph service exception

In the logs, I can see

2024-03-26 16:11:47.424 +00:00 [ERR] Code in PreScanningAsync failed. This can happen when the first enumerated site collection is locked
HttpResponseCode: 403
Code: Authorization_RequestDenied
Message: Insufficient privileges to complete the operation.

**Comment by femilovechild** [comment]
Never mind. Figured it out. Wrong set of permissions on the azure app

**Comment by magicofpankaj** [comment]
I have all the required permissions. I am also facing same issue.
Can you please tell me the permissions required to run the tool?

**Comment by RomanTheKing** [comment]
This guy solved the puzze:

**Comment by pxm296** [comment]
I got the same issue "Assessment job not started due to error: Microsoft Graph service exception". After giving additional permissions on azure app as @RomanTheKing  mentioned, the permission issue is resolved. 

But now I am getting "**Assessment job not started due to error: Max number of parallel assessments reached**" any idea.?

I tried microsoft365-assessment.exe stop but it still showing the jobs with Queue status 

![Image](https://github.com/user-attachments/assets/d5a18104-90af-49eb-978a-e602b3a6a944)

**Comment by purna429** [comment]
I got the same issue "Assessment job not started due to error: Microsoft Graph service exception". After giving additional permissions on azure app as @RomanTheKing  mentioned, the permission issue is resolved. 

But now I am getting "**Assessment job not started due to error: Max number of parallel assessments reached**" any idea.?

I tried microsoft365-assessment.exe stop but it still showing the jobs with Queue status 

![Image](https://github.com/user-attachments/assets/d5a18104-90af-49eb-978a-e602b3a6a944)

**Comment by marleyhehe** [comment]
> I got the same issue "Assessment job not started due to error: Microsoft Graph service exception". After giving additional permissions on azure app as [@RomanTheKing](https://github.com/RomanTheKing) mentioned, the permission issue is resolved.
> 
> But now I am getting "**Assessment job not started due to error: Max number of parallel assessments reached**" any idea.?
> 
> I tried microsoft365-assessment.exe stop but it still showing the jobs with Queue status
> 
> ![Image](https://github.com/user-attachments/assets/d5a18104-90af-49eb-978a-e602b3a6a944)

You need to cancel those, that we're started with wrong settings
